### ISSUE TITLE
Requested changes

### ISSUE THREAD

**Issue by dwdv** [dwdv/color-editor#21]
Chromaticity diagram: #3 
- [x] complementary wavelength
- [x] labels, axis
- [x] spectral data interpolation/smooth drawing
- [ ] saturation, hue, ...
- [x] spectral line hover and color spectrum
- [ ] sliders similar to other views
- [x] scale properly
- [x] plot typical computer screen gamut (and some more, maybe)

Image comparison:
- [x] labels
- [ ] fix sat and val (after hsv conv) when neg #14 
- [X] change one or (optional) multiple channel to other color space
- [x] quad view: comb + comb histo below, three channels, each with histogram below; with gui and orig img on left or right (goal is to eliminate whitespace)
- [x] colorize lab and luv in  a-b-/u-v-specific colors instead of yellow-blue

3d view: #11 
- [x] axes, maybe faded + labels
- [x] labels (also orbit control help)
- [x] sliders, similar to other views
- [x] scale properly
- [ ] fix lab sphere #20 LCh? luv?
- [x] fix FOV
- [x] quad view

misc:
- [x] integration, deployment, no external deps #17 
- [x] tabs (prefered) or dropdown for view selection #12 
- [x] kill d50, stick to d65
- [x] inc fps
- [x] datgui scaling behaviour on mouse scale
- [x] change readme

optional:
- [ ] refactor css
- [ ] refactor js #15
- [ ] refactor html and shaders
- [x] orbit controls too fast when fps are unbound
- [x] delta to 1e-10
